[package]
name = "bond"
description = "A fast fixed-income calculation library"
version = "0.0.1"
license = "MIT"
authors = ["Edmund Kump <ekump@mac.com>"]
edition = "2018"

[dependencies]
bigdecimal = "0.0.15"
